### ISSUE TITLE
Not works if css contains inline comments

### ISSUE THREAD

**Issue by harisjayadev** [sindresorhus/gulp-rework#12]
Not works if css contains inline comments like below. Throwing error

background: #aaaaaa/*{bgColorOverlay}*/ url(images/ui-bg_flat_0_aaaaaa_40x100.png)/*{bgImgUrlOverlay}*/ 50%/*{bgOverlayXPos}*/ 50%/*{bgOverlayYPos}*/ repeat-x/*{bgOverlayRepeat}*/;

**Comment by sindresorhus** [comment]
Open an issue on the Rework project. This is just a wrapper plugin.
